In [1]:
import cv2
import numpy as np

In [20]:
base=cv2.imread('./images/tornillo_7.jpg')
# change=cv2.imread('./images/headphones.jpg')

In [21]:
 #blur image 
# im1=cv2.blur(im1,(5,5))
# im1=cv2.GaussianBlur(im1,(5,5),0)
im1=cv2.medianBlur(base,5)

im1=cv2.cvtColor(im1,cv2.COLOR_BGR2GRAY)
#set threshold
# _,t=cv2.threshold(im1,100,255,cv2.THRESH_BINARY_INV)

# c,b=cv2.findContours(t,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)

# im1=cv2.drawContours(base,c,-1,(0,255,0),1)

#finding the screw circular shape and center
circles=cv2.HoughCircles(im1,cv2.HOUGH_GRADIENT,1,20,param1=50,param2=30,minRadius=0,maxRadius=0)

# assert bool(circles) is not False,"no circles obtained"
circles=np.uint16(np.around(circles))

for i in circles[0,:]:
    cv2.circle(base,(i[0],i[1]),i[2],(0,255,0),2) #borde del tornillo
    cv2.circle(base,(i[0],i[1]),2,(0,0,255),3) #centro del tornillo

cv2.circle(base,(base.shape[1]//2,base.shape[0]//2),2,(255,0,0),3)#centro de la imagen

array([[[161, 163, 163],
        [159, 161, 161],
        [157, 159, 159],
        ...,
        [171, 172, 176],
        [169, 172, 177],
        [169, 172, 177]],

       [[160, 162, 162],
        [160, 162, 162],
        [159, 161, 161],
        ...,
        [171, 172, 176],
        [169, 172, 176],
        [170, 173, 177]],

       [[160, 162, 162],
        [161, 163, 163],
        [162, 164, 164],
        ...,
        [171, 173, 174],
        [170, 174, 175],
        [170, 174, 175]],

       ...,

       [[172, 171, 175],
        [173, 172, 174],
        [173, 172, 176],
        ...,
        [178, 180, 181],
        [178, 180, 181],
        [179, 181, 182]],

       [[173, 172, 174],
        [175, 175, 175],
        [175, 174, 176],
        ...,
        [178, 180, 181],
        [178, 180, 181],
        [178, 180, 181]],

       [[173, 173, 173],
        [176, 177, 175],
        [177, 177, 177],
        ...,
        [178, 180, 181],
        [177, 179, 180],
        [177, 179, 180]]

In [22]:
tornillos=[] #x,y
for i in circles[0,:]:
    tornillos.append(i[0])
    tornillos.append(i[1])

In [23]:
tornillos

[78, 106]

In [24]:
centro=[base.shape[0]//2,base.shape[1]//2]
centro

[119, 87]

In [25]:
np.subtract(tornillos,centro)
#movimento[x,y]

array([-41,  19])

In [18]:
circles

array([[[ 78, 106,  17]]], dtype=uint16)

In [ ]:
#making object contour
_,con=cv2.threshold(im2,150,255,cv2.THRESH_BINARY)

con,_=cv2.findContours(con,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(change,con,-1,(0,255,0),10,cv2.LINE_AA)

In [26]:
# img=cv2.resize(im1,im1.shape[:2])
cv2.imshow('cambio',base)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [24]:
base.shape[0]

3